# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
      args: ["--maxkb=8192"]
    - id: check-ast
    - id: name-tests-test
    - id: check-case-conflict
    - id: check-yaml
    - id: check-toml
    - id: check-xml
    - id: check-json

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
    - id: black-jupyter

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    - id: ruff
        # args: [ --fix ]
    - id: ruff-format

-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
    - id: markdownlint
      args: ["-r", "~MD024"]

-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
    - id: docker-compose-check

-   repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
    - id: commitizen  # pre-commit install --hook-type commit-msg
